### ISSUE TITLE
Latest code release (1.2.1) doesn't contain latest params.pp code fix

### ISSUE THREAD

**Issue by v4ld3r5** [abstractitptyltd/puppet-sudo#16]
Hi,
I've deployed the latest module version using R10K and when testing I get the following issue, it had to do with the OS names not in quotes (I'm running Puppet v4.7)

_Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Resource type not found: Debian at /etc/puppetlabs/code/environments/production/modules/sudo/manifests/params.pp:7:71 on node xxx_

Noticed v1.2.1 was released on 28th Nov 2014, while this was already fixed later on at 0515a875d652802ab444acb02553588ae0c0af05

Is there any plan to release a new version soon?
Best regards

**Comment by rendhalver** [comment]
Hi,

I will get a new release out soon.

Thanks for the reminder.

**Comment by rendhalver** [comment]
I just pushed out version 1.2.2
