### ISSUE TITLE
Release a New Version

### ISSUE THREAD

**Issue by benhocker** [abstractitptyltd/puppet-sudo#17]
Can you release a new version? I don't see a new version since 1.2.1 in 2014. I'd prefer to freeze on a release rather than a commit hash.

**Comment by rendhalver** [comment]
Thanks for the reminder @benhocker.
I will get a release pushed out soon.

**Comment by benhocker** [comment]
Thanks @rendhalver!

**Comment by mihall-primus** [comment]
Any chance of pushing out that release?

**Comment by rendhalver** [comment]
I will do my best to get that sorted soon.

**Comment by rendhalver** [comment]
I just pushed out version 1.2.2
