### ISSUE TITLE
commands not treated as array in templates/rule.erb

### ISSUE THREAD

**Issue by rbeede** [abstractitptyltd/puppet-sudo#6]
The @commands should be treated as a comma separated list since that is allowed for sudo::rule { commands => [] }

The recommended change:
    
    <% if comment -%>
    #
    # <%= comment %>
    <% end -%>
    <%= who %>	<%= servers %> = (<%= runas %>) <% if nopass == true %>NOPASSWD:<% end %> <%= @commands.class == Array ? @commands.join(", ") : @commands %>

**Comment by rendhalver** [comment]
Commands is definitely treated as an array now.
I will close this.

Thanks again.
